services:
  test:
    container_name: ref-bdd
    environment:
      - http_proxy=http://192.168.1.10:2080
      - https_proxy=http://192.168.1.10:2080
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      args:
        - http_proxy=http://192.168.1.10:2080
      tags:
        - bdd-img:latest
    volumes:
      - ./vols/reports:/app/cypress/reports
      - ./vols/screenshots:/app/cypress/screenshots
