services:
  test:
    container_name: ref-testing
    network_mode: "host"
    environment:
      - http_proxy=http://127.0.0.1:2334
      - https_proxy=http://127.0.0.1:2334
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ref-testing-vol:/app/cypress/reports
      - ref-testing-vol:/app/cypress/screenshots
      - ref-testing-vol:/app/cypress/videos

volumes:
  ref-testing-vol:
